
module.exports = {
    login: '登录',
    mPage: 'E企管',
    forgetPassword: '修改密码',
    car3Trips: '行程管理',
    car3TripsSearch: '行程搜索',
    car3TripDetail: '行程详情',
    car3TripGroup: '选择行程分组',
    car3TripArrangeCar: '委派司机车辆',
    car3TripsSpell: '拼单',
    car3SpellMain: '选定主行程',
    car3SpellSuccess: '拼单成功',
    car3SpellDetail: '查看拼单',
    car3TripFee: '费用设置',
    car3TripTrack: '行程轨迹',
    car3Monitor: '车辆监控',
    car3CarTrack: '车辆轨迹',
    car3CreateOrder: '发起行程',
    car3CreateGroup: '选择行程分组',
    car3CreateApplicant: '选择申请人',
    car3MsgList: '公务车',
};
